# Personal Information
title: "JEEJY30 - Security & Development Portfolio"
description: "Personal portfolio showcasing cybersecurity research, development projects, and technical writeups"
url: "https://jeejy30.github.io"
baseurl: ""

# Author Information
author:
  name: "JEEJY30"
  title: "Security Researcher & Full-Stack Developer"
  bio: "Passionate about cybersecurity, web development, and sharing knowledge through detailed writeups and professional experiences."
  email: "your.email@example.com"
  github: "JEEJY30"
  linkedin: "your-linkedin-username"
  twitter: "your-twitter-handle"

# Technical Settings
markdown: kramdown
highlighter: rouge
permalink: /writeups/:year/:month/:day/:title/

# Exclude files
exclude:
  - vendor/
  - Gemfile*
  - README.md
  - .github/

# Essential plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections for organizing content
collections:
  experiences:
    output: true
    permalink: /experience/:name/
  projects:
    output: true
    permalink: /projects/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "JEEJY30"
  - scope:
      path: ""
      type: "experiences"
    values:
      layout: "experience"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"