# Your site info
title: "Zero to Hero Documentation"
description: "Master our tools with comprehensive guides and tutorials"
url: "https://jeejy30.github.io"
baseurl: "/Zero-to-Hero"
repository: "JEEJY30/Zero-to-Hero"

# GitHub info (for links)
github_username: "JEEJY30"
github_repo: "Zero-to-Hero"

# Technical stuff
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github/