# Your site info
title: "My Documentation Site"
description: "Everything about my project"
url: "https://jeejy30.github.io"

# Technical stuff (don't change)
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Main menu items
navigation:
  - name: "Home"
    link: "/"
  - name: "Docs"
    link: "/docs/"
  - name: "Blog" 
    link: "/blog/"

# Documentation sidebar menu
docs_sidebar:
  - title: "Getting Started"
    items:
      - name: "Installation"
        link: "/docs/installation"
      - name: "Quick Start"
        link: "/docs/getting-started"
  - title: "Configuration"
    items:
      - name: "Basic Setup"
        link: "/docs/basic-setup"
      - name: "Advanced"
        link: "/docs/advanced"
  - title: "Help"
    items:
      - name: "Troubleshooting"
        link: "/docs/troubleshooting"
      - name: "FAQ"
        link: "/docs/faq"